# Basics
baseURL = "https://blog.sldk.de"
title   = "Leonid Koftun"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
DefaultContentLanguage = "en"

# Google Analytics
googleAnalytics = "G-4S8T5XN1Q2"

# Non-standard?
disqusShortname = "blog-sldk-de"

# Build settings
buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

# Enable things
enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true

[permalinks]
  posts = "/:year/:month/:title/"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "2006-01-02"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = "Software Engineer"

  # Metadata mostly used in document's head
  description = "Leonid's blog"
  keywords = ""
  images = [""]

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
   gitUrl = "https://github.com/sladkoff/sladkoff.github.io/commit/"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = ["/css/prism.css", "/css/style.css"]
  customJS  = ["/js/prism.js"]

  # Default theme "light" or "dark"
  defaultTheme = "light"
  themeColor = "#2ecc71"

  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:leonid.koftun@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/sladkoff"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/leonidkoftun"


  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/sladkoff2"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/sladkovik"

  [[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/1510659"

[languages]
  [languages.en]
    subtitle  = "Software Engineer"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
