baseURL = "https://sladkoff.github.io"
title   = "Leonid Koftun"

DefaultContentLanguage = "en"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
disqusShortname = "blog-sldk-de"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Leonid Koftun"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "2006-01-02"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Leonid's blog"
  keywords = ""
  images = [""]

  homeSubtitle = "Software Engineer"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = ["/css/prism.css", "/css/style.css"]
  customJS  = ["/js/prism.js"]

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "light"
  themeColor = "#2ecc71"

  # Colors for favicons
  [params.favicon.color]
    mask = "#2ecc71"
    msapplication = "#2ecc71"
    theme = "#2ecc71"

  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    # Set to a valid CSS color to change the cursor in the logo.
    # logoColor    = "#67a2c9"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/"

  [[params.social]]
    name = "email"
    url  = "mailto:leonid.koftun@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/sladkoff"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/leonid-koftun-48528953/"

  [[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/1510659"

[languages]
  [languages.en]
    subtitle  = "Software Engineer"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.de]
    subtitle  = "Software Engineer"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
